# frozen_string_literal: true

source "https://rubygems.org"

gem "pry"
gem "sinatra-activerecord"
gem "activerecord"
gem "rake"
gem "sqlite3"
gem "require_all"
gem "rspec"
gem "sinatra"
# gem "rails"
