Doctor.create(name:"", location: "", license_number: )
Doctor.create(name:"", location: "", license_number: )
Doctor.create(name:"", location: "", license_number: )
Doctor.create(name:"", location: "", license_number: )
Doctor.create(name:"", location: "", license_number: )
Doctor.create(name:"", location: "", license_number: )